version: "3"
services:
  frontend-server:
    image: thetiptop2023667/tiptopfront:latest
    ports:
      - "80:80"
    environment:
      - API_URI=http://15.237.223.123:8080
    networks:
      - springmysql-net
    depends_on:
      - mysqldb
  backend-server:
    image: thetiptop2023667/tiptopback:latest
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
      - spring.datasource.url=jdbc:mysql://15.237.223.123:3306/tiptopdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - server.servlet.context-path=/api
      - server.port=8080
      - jwt.secret=javainuse
    networks:
      - springmysql-net
    depends_on:
      - mysqldb
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 6G # Adjust as per your requirement
        reservations:
          memory: 6G # Adjust as per your requirement

  mysqldb:
    image: mysql:5.7
    container_name: tiptopbase
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tiptopdb
    ports:
      - "3306:3306"



networks:
  springmysql-net:
